name: CI/CD Workflow

on:
  push:
    branches: [ main ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
        working-directory: ${{ github.workspace }}
  
  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      
      - name: Install Dependencies
        run: npm install
        working-directory: ${{ github.workspace }}
      
      - name: Run semantic release
        run: npx semantic-release
        working-directory: ${{ github.workspace }}
      
      - name: Print package.json version (before)
        run: |
          echo "package.json version (before): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}
      
      - name: Fetch latest commit
        run: |
          git fetch
          git reset --hard origin/main
      
      - name: Print package.json version (after)
        run: |
          echo "package.json version (after): $(jq -r .version package.json)"
        working-directory: ${{ github.workspace }}